install.packages(c("bitops",
                   "car",
                   "caTools",
                   "devtools",
                   "dplyr",
                   "ez",
                   "gdata",
                   "ggplot2",
                   "haven",
                   "Hmisc",
                   "htmltools",
                   "knitr",
                   "plyr",
                   "ProjectTemplate",
                   "R.matlab",
                   "reshape",
                   "reshape2",
                   "rmarkdown",
                   "roxygen2",
                   "stringr",
                   "tidyr",
                   "tidyverse",
                   "yaml"))

devtools::install_github("hallez/halle", subdir="halle")
