install.packages(lib="/group/dml/hrzucker/local-r-pkgs/", c("bitops",
                   "car",
                   "caTools",
                   "coin",
                   "devtools",
                   "dplyr",
                   "emmeans",
                   "ez",
                   "furrr",
                   "gdata",
                   "ggplot2",
                   "haven",
                   "Hmisc",
                   "htmltools",
                   "knitr",
                   "plyr",
                   "prettyunits",
                   "ProjectTemplate",
                   "R.matlab",
                   "readxl",
                   "reshape",
                   "reshape2",
                   "rmarkdown",
                   "roxygen2",
                   "stringr",
                   "tictoc",
                   "tidyr",
                   "tidyverse",
                   "yaml"))

devtools::install_github("hallez/halle", subdir="halle",lib="/group/dml/hrzucker/local-r-pkgs/")
